stages:
  - autotest

run_tests:
  image: mcr.microsoft.com/playwright/python:v1.49.1-jammy
  stage: autotest
  before_script:
  - pip install -r requirements.txt
  script:
    - pytest --bn=remote_chrome --tmsUrl=${TMS_URL} --tmsPrivateToken=${TMS_PRIVATE_TOKEN} --tmsProjectId=${TMS_PROJECT_ID} --tmsConfigurationId=${TMS_CONFIGURATION_ID} --tmsCertValidation=${TMS_CERT_VALIDATION} --tmsAdapterMode=${TMS_ADAPTER_MODE}

