stages:
  - autotest

run_tests:
  image: python:3.10
  stage: autotest
  before_script:
  - pip install -r requirements.txt
  script:
    - pytest --testit --tmsUrl=${TMS_URL} --tmsPrivateToken=${TMS_PRIVATE_TOKEN} --tmsProjectId=${TMS_PROJECT_ID} --tmsConfigurationId=${TMS_CONFIGURATION_ID} --tmsCertValidation=${TMS_CERT_VALIDATION} --tmsAdapterMode=${TMS_ADAPTER_MODE}

