

class TendersLocators:
    INPUT_NOTICE_WRAPPER = '//div[@class="search__input form-input form-input--ctrl form-input--btn-clear"]'
    INPUT_NOTICE = "//div[@class='search__input form-input form-input--ctrl form-input--btn-clear']//input"
    INPUT_REGION = "//div[@class='form-input form-input--no-label form-input--ctrl']//input"
    BUTTON_SEARCH = '//button[@class="form-input__ctrl btn"]'
    CLEAR_BUTTON_SEARCH = '//button[@class="form-input__ctrl form-input__ctrl--clear btn"]'
    CLEAR_BUTTON_REGION = '//div[@class="modal__header-content"]//button'
    LOADER_404 = '//div[@class="loader loader--404"]//div[@class="loader__legend"]'
    COUNT_FOUND_TENDERS = '//div[@class="search__legend"]'
    CHOOSE_REGION_BUTTON = '//button[@class="mark-ctrl"]'
    ELEMENT_REGION = '//button[@class="dropdown__button"]'
    TENDER_SELECT_SORT = '//button[@class="select__body"]'
    TENDER_SELECT_SORT_BUTTON = '//button[@class="select__button"]'
    TENDER_SELECT_SORT_DROPDOWN = '//div[@class="select__dropdown"]'
    TENDER_PURCHASE_BY_FORM = '//div[@class="form"][2]'
    TENDER_PURCHASE_BY_CHECKBOX = '//label[@class="form-checkbox__label"]'
    TENDER_PURCHASE_BY_CHECKBOX_CLEAR = '//div[@class="form"][2]//button'
    TENDER_OPEN_SAVE_QUERY = '//button[@class="link-btn link-btn--offset-bottom"]'
    TENDER_PRICE_INPUT_BEFORE= '//input[@id="minApplicationGuarantee"]'
    TENDER_SEARCH_ORGANIZATION = '//input[@aria-label="ИНН организатора"]'
    TENDER_FILTER_BUTTON = '//button[@class="btn btn--secondary-outline btn--wide btn--icon"]'
    TENDER_MODAL_INPUT = '//div[@class="modal__header-content"]//input'
    TENDER_LIST_CHECKBOX = '//ul[@class="form-el-list"]//label'
    TENDER_MODAL_FOOTER_BUTTONS = '//div[@class="modal__footer modal-footer modal-footer--style-2 modal-footer--buttons-line"]//button'
    TENDER_SEARCH_FOOTER_BUTTONS = '//div[@class="modal__footer modal-footer modal-footer--style-2 modal-footer--buttons-grid"]//button'
    TENDER_FILTER_LIST = '//ul[@class="filter-list"]'
    TENDER_SEARCH_ACCEPT = '//button[@class="modal-footer__btn btn btn--primary btn--medium-responsive btn--wide"]'
    TENDER_COUNTER_SAVE_QUERY = '//span[@class="link-btn__num"]'
    TENDER_SUCCESS_MODAL_BUTTON = '//div[@class="info__footer"]//button'
    TENDER_LIST_SAVE_QUERY = '//label[@class="dropdown__label"]'